export const roles = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  TECHNICIAN: 'TECHNICIAN',
  ADMIN: 'ADMIN',
});

export const requestStatuses = Object.freeze({
  PENDING: 'PENDING',
  MATCHING: 'MATCHING',
  QUOTED: 'QUOTED',
  BOOKED: 'BOOKED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const bookingTransitions = Object.freeze({
  CONFIRMED: ['TECHNICIAN_ON_THE_WAY', 'CANCELLATION_REVIEW', 'CANCELLED'],
  TECHNICIAN_ON_THE_WAY: ['IN_PROGRESS', 'CANCELLATION_REVIEW'],
  IN_PROGRESS: ['AWAITING_CUSTOMER_CONFIRMATION', 'CANCELLATION_REVIEW'],
  AWAITING_CUSTOMER_CONFIRMATION: ['COMPLETED', 'DISPUTED'],
  CANCELLATION_REVIEW: ['CANCELLED', 'IN_PROGRESS', 'DISPUTED'],
  DISPUTED: ['COMPLETED', 'CANCELLED'],
  COMPLETED: [],
  CANCELLED: [],
});

export const complaintTransitions = Object.freeze({
  PENDING: ['PROCESSING', 'RESOLVED', 'REJECTED'],
  PROCESSING: ['WAITING_FOR_CUSTOMER', 'WAITING_FOR_TECHNICIAN', 'RESOLVED', 'REJECTED'],
  WAITING_FOR_CUSTOMER: ['PROCESSING', 'RESOLVED', 'REJECTED'],
  WAITING_FOR_TECHNICIAN: ['PROCESSING', 'RESOLVED', 'REJECTED'],
  RESOLVED: ['REOPENED'],
  REJECTED: ['REOPENED'],
  REOPENED: ['PROCESSING'],
});

export function canTransition(transitions, from, to) {
  return Boolean(transitions[from]?.includes(to));
}
